version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-dev-client
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/app
networks:
  default:
    external:
      name: timelineserver_default
