version: "3"
services:
  dev-client:
    build:
      context: ../
      dockerfile: docker/Dockerfile-dev-client
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ../:/app
  dev-server:
    build:
      context: ../
      dockerfile: docker/Dockerfile-dev-server
    ports:
      - "3999:3999"
    volumes:
      - ../:/app
  db:
    image: gijsjan/postgresql:1.0
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
    ports:
      - "5432:5432"
    volumes:
      - timeline-data:/pgdata
volumes:
  timeline-data:

