dev:
  entrypoint: "./entrypoint.sh"
  environment:
    - SSH_AUTH_SOCK=/ssh-agent
  image: gijsjan/webdev:1.3
  links:
    - db
  ports:
    - "3001:3001"
  volumes:
    - ..:/home/developer/timeline-client
    - ../../timeline-server:/home/developer/timeline-server
    - ./tmuxinator.yml:/home/developer/.tmuxinator/project.yml
    - ./entrypoint.sh:/home/developer/entrypoint.sh
    - ~/.ssh:/home/developer/.ssh
    - ${SSH_AUTH_SOCK}:/ssh-agent
db:
  image: gijsjan/postgresql:1.0
  environment:
    - POSTGRES_PASSWORD=docker
    - POSTGRES_USER=docker
  ports:
    - "5432:5432"
  volumes:
    - timeline-data:/var/lib/postgresql
